<?php

$Frageworte = array(
	0 => array('Grammatik' => 'Nominativ', 'Fragewort'	=> 'Wer'),	
	1 => array('Grammatik' => 'Nominativ', 'Fragewort'	=> 'Was'	),
	2 => array('Grammatik'=> 'Akkusativ', 'Fragewort'	=> 'Wen'),	
	3 => array('Grammatik'=> 'Akkusativ', 'Fragewort'	=> 'Was'	),
	4 => array('Grammatik'=> 'Dativ', 'Fragewort'	=> 'Wem'),	
	5 => array('Grammatik'=> 'Genitiv', 'Fragewort'	=> 'Wessen'), 	
	6 => array('Grammatik'=> 'Situativ', 'Fragewort'	=> 'Wo'),	
	7 => array('Grammatik'=> 'Direktiv', 'Fragewort'	=> 'Wohin'),	
	8 => array('Grammatik'=> 'Direktiv', 'Fragewort'	=> 'Woher'),
	9 => array('Grammatik'=> 'Präpositional', 'Fragewort'	=> 'Mit wem'),	
	10 => array('Grammatik'=> 'Präpositional', 'Fragewort'	=> 'Woran'),
	11 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Wann'),
	12 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Wie'), 
	13 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Für wie'), 
	14 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Wie oft'),	
	15 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Ab wann'),	
	16 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Bis wann'),	
	17 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Seit wann'),
	18 => array('Grammatik'=> 'temporal', 'Fragewort'	=> 'Von wann bis wann'),
	19 => array('Grammatik'=> 'Uhrzeit', 'Fragewort'	=> 'Wie viel Uhr'), 
	20 => array('Grammatik'=> 'Uhrzeit', 'Fragewort'	=> 'Wie spät'),	
	21 => array('Grammatik'=> 'Uhrzeit', 'Fragewort'	=> 'Um wie viel Uhr'),
	22 => array('Grammatik'=> 'Ort', 'Fragewort'	=> 'Wo'),	
	23 => array('Grammatik'=> 'Richtung', 'Fragewort'	=> 'Wohin'),	
	24 => array('Grammatik'=> 'Herkunft', 'Fragewort'	=> 'Woher'),	
	25 => array('Grammatik'=> 'kausal', 'Fragewort'	=> 'Warum'),	
	26 => array('Grammatik'=> 'kausal', 'Fragewort'	=> 'Weshalb'),	
	27 => array('Grammatik'=> 'kausal', 'Fragewort'	=> 'Weswegen'),	
	28 => array('Grammatik'=> 'kausal', 'Fragewort'	=> 'Wieso'),	
	29 => array('Grammatik'=> 'kausal', 'Fragewort'	=> 'Aus welchem Grund'),	
	30 => array('Grammatik'=> 'final', 'Fragewort'	=> 'Wozu'),	
	31 => array('Grammatik'=> 'Auswahl', 'Fragewort'	=> 'Welche'), 
	32 => array('Grammatik'=> 'Auswahl', 'Fragewort'	=> 'An welchem'), 
	33 => array('Grammatik'=> 'Auswahl', 'Fragewort'	=> 'Mit welchem'), 
	34 => array('Grammatik'=> 'Qualität', 'Fragewort'	=> 'Was für'), 
	35 => array('Grammatik'=> 'Qualität', 'Fragewort'	=> 'Mit was für'), 
	36 => array('Grammatik'=> 'Nominativ', 'Fragewort'	=> 'An was'), 
	37 => array('Grammatik'=> 'Dativ', 'Fragewort'	=> 'Mit was'), 
	38 => array('Grammatik'=> 'Qualität', 'Fragewort'	=> 'An was für'), 
	39 => array('Grammatik'=> 'modal', 'Fragewort'	=> 'Wie'),
	40 => array('Grammatik'=> 'Menge', 'Fragewort'	=> 'Wie viel	'),
	41 => array('Grammatik'=> 'Menge', 'Fragewort'	=> 'Wie viele'), 
	42 => array('Grammatik'=> 'Maße', 'Fragewort'	=> 'Wie weit'),	
	43 => array('Grammatik'=> 'Maße', 'Fragewort'	=> 'Wie tief	'),
	44 => array('Grammatik'=> 'Maße', 'Fragewort'	=> 'Wie alt'),	
	45 => array('Grammatik'=> 'Gewichte', 'Fragewort'	=> 'Wie schwer'),	
	46 => array('Grammatik'=> 'Prädikativ', 'Fragewort'	=> 'Wie	ist'),	
	47 => array('Grammatik'=> 'Adverbial', 'Fragewort'	=> 'Wie	singt')
);	



?>